export enum EventType {
	All = "",
	CategoryCreated = "category-created",
	CategoryRemoved = "category-removed",
	CategoryRestored = "category-restored",
	CategoryUpdated = "category-updated",
	CommentCreated = "comment-created",
	CommentDeleted = "comment-deleted",
	CommentUpdated = "comment-updated",
	GameCoversUpdated = "game-covers-updated",
	GameCreated = "game-created",
	GameModeratorCreated = "game-moderator-created",
	GameModeratorRemoved = "game-moderator-removed",
	GameModeratorUpdated = "game-moderator-updated",
	GameNewsPostCreated = "game-news-post-created",
	GameNewsPostEdited = "game-news-post-edited",
	GameNewsPostRemoved = "game-news-post-removed",
	GameRestored = "game-restored",
	GameUpdated = "game-updated",
	GamerequestReviewed = "gamerequest-reviewed",
	LevelCreated = "level-created",
}
