export enum Language {
	en = "en-US",
	se = "se-SV",
	ar = "ar-EG",
	es = "es-ES",
	de = "de-DE",
	fr = "fr-FR",
	hi = "hi-IN",
	id = "id-ID",
	it = "it-IT",
	ja = "ja-JP",
	ko = "ko-KR",
	nl = "nl-NL",
	pl = "pl-PL",
	pt = "pt-BR",
	ru = "ru-RU",
	tr = "tr-TR",
	zh = "zh-CN",
}
