// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/index.tsx";
import * as $1 from "./pages/api/discord/interactions.ts";
import * as $2 from "./pages/api/discord/bot_info.ts";
import * as $3 from "./pages/api/discord/reload.ts";
import * as $4 from "./pages/api/discord/token.ts";
import * as $5 from "./pages/admin.tsx";

const routes = {
	pages: {
		"./pages/index.tsx": $0,
		"./pages/api/discord/interactions.ts": $1,
		"./pages/api/discord/bot_info.ts": $2,
		"./pages/api/discord/reload.ts": $3,
		"./pages/api/discord/token.ts": $4,
		"./pages/admin.tsx": $5,
	},
	baseUrl: import.meta.url,
};

export default routes;
