name: Deno

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --config ./deno.jsonc --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

  publish:
    if: github.repository == 'AnInternetTroll/speedrunbot-slash' && github.ref == 'refs/heads/master',
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

    steps:
      - name: Update commands
        run: deno run --allow-net=gateway.discord.gg,discord.com --allow-env --allow-read=. --no-check src/client.ts -u
